### ISSUE TITLE
Invalid scheme error

### ISSUE THREAD

**Issue by tfwright** [fidr/peppermint#1]
Hi, thank for your work on this lib.

I notice that there doesn't seem to be any format checking on the url argument, so if invalid options like nil, "test" , "", result in a function error:

```
Traceback (most recent call last):
  File "lib/peppermint.ex", line 266, in Peppermint.scheme/1 (peppermint)
  File "lib/peppermint.ex", line 80, in Peppermint.connect/2 (peppermint)
  File "lib/peppermint.ex", line 57, in Peppermint.request/3 (peppermint)
```

I think it would be preferable to return an error Tuple in those cases.

Version: `"0.3.0", "8a9fe95c799945543bb5b8067f4b9e9af20f5e1a8ece707ce3731c97128a4e45"`

I'd be happy to open a PR if that'd be helpful.

**Comment by fidr** [comment]
Hi, that sounds like a good idea. I’d welcome a PR for that!
